on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.0"
          elixir-version: "1.12.0"
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: docker-compose up -d
      - run: mix deps.get
      - run: mix credo --strict
        continue-on-error: true
      - run: mix format --check-formatted
        continue-on-error: true
      - run: mix test
      - run: mix dialyzer
